### ISSUE TITLE
2 branches und deploy pending??

### ISSUE THREAD

**Issue by Bia-Ka** [FOM-ifes/Factsheets#2]
Hallo - wer kann helfen? Hier scheint irgendetwas mit Git falsch zu laufen....
Matthias (gestern) und Karsten (heute) haben commits abgesetzt, aber irgendwie hängt das fest???

**Comment by NMarkgraf** [comment]
Sollte alles gehen. Wenn dann dieses Issue schliessen. Danke!

**Comment by Bia-Ka** [comment]
Jetzt sind Karstens Änderungen zwar drin, aber wir haben zwei Branches: master und main. Meine Änderungen vom Tag davor sind in dem anderen Branch. Wie bekommt man das jetzt wieder zusammen?

**Comment by NMarkgraf** [comment]
Jetzt sind auch deine drin! -- "MASTER" nennt man eine branch nicht mehr, sie heissen nun "MAIN" ... Fragt euch wieso ;-)

**Comment by MGehrke** [comment]
hihi, ich hatte erst gedacht, das ist eine neue Branch für das neue Mastermodul, bis ich gemerkt habe, dass die Inhalte identisch sind.

**Comment by Bia-Ka** [comment]
Argh - ich hoffe, das passiert jetzt nicht öfter? Ich verstehe es leider gar nicht. Meine Änderungen waren zuerst und da hieß es noch Master. Dann kamen Karstens Änderungen, die in Main landeten, bzw. erst gar nicht landeten.
Kann mir das jemand kurz erklären?

**Comment by NMarkgraf** [comment]
Okay, ich versuch es mal.

Also es wurde eine neue Brache angelegt. Die heißt "main" und nicht mehr vc    r "master". Karsten hat vermutlich zu erst einen pull vor dem Commit einen pull gemacht und ist daher automatisch im main gelandet. Du vermutlich hast nur einen Commit gemacht und warst im altern master. Ich habe jetzt alles in die Brache master in main "kopiert", master gelöscht und nun sollte alles wieder laufen.

Unsere default branch heisst nun also main (und nicht mehr master).

Ich hoffe das hilft dir?

**Comment by Bia-Ka** [comment]
Ein wenig wird es klarer. :-) 
Danke, Norman!
